//! Renderers for lab-assistant handoff reports.
//!
//! Keep the report serialization separate from sequence editing helpers so the
//! eventual renderer-crate extraction can move this module mechanically.

use crate::engine::{
    LabAssistantInstructionsExport, LabAssistantVisualRow,
    zip_store::{StoredZipMember, build_stored_zip_archive},
};

#[derive(Debug, Clone)]
pub(crate) struct LabAssistantEmbeddedImage {
    pub(crate) visual_id: String,
    pub(crate) label: String,
    pub(crate) file_name: String,
    pub(crate) bytes: Vec<u8>,
    pub(crate) width_px: usize,
    pub(crate) height_px: usize,
}

impl LabAssistantEmbeddedImage {
    pub(crate) fn visual_row(&self, source: &str) -> LabAssistantVisualRow {
        LabAssistantVisualRow {
            visual_id: self.visual_id.clone(),
            label: self.label.clone(),
            format: "png".to_string(),
            source: source.to_string(),
            width_px: self.width_px,
            height_px: self.height_px,
        }
    }
}

pub(crate) fn render_markdown(export: &LabAssistantInstructionsExport) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", export.title));
    out.push_str(&format!("- Schema: `{}`\n", export.schema));
    out.push_str(&format!("- Format: `{}`\n", export.output_format.as_str()));
    out.push_str(&format!(
        "- Audience: {}\n",
        markdown_escape(&export.audience)
    ));
    out.push_str("- Generated by GENtle from selected operation records.\n");
    if let Some(run_id) = export.run_id_filter.as_deref() {
        out.push_str(&format!("- Run ID: `{}`\n", markdown_escape(run_id)));
    }
    out.push('\n');

    push_markdown_list(&mut out, "Summary", &export.summary_lines);
    push_markdown_list(&mut out, "Safety and Scope", &export.safety_lines);
    push_markdown_visuals(&mut out, export);
    push_markdown_materials(&mut out, export);
    for section in &export.step_sections {
        push_markdown_list(&mut out, &section.heading, &section.steps);
    }
    push_markdown_list(&mut out, "Checkpoints", &export.checkpoint_lines);
    push_markdown_list(&mut out, "Record Keeping", &export.record_keeping_lines);
    if !export.warning_lines.is_empty() {
        push_markdown_list(&mut out, "Warnings", &export.warning_lines);
    }
    out
}

pub(crate) fn render_odt(
    export: &LabAssistantInstructionsExport,
    images: &[LabAssistantEmbeddedImage],
) -> Result<Vec<u8>, String> {
    let content_xml = render_odt_content(export, images);
    let manifest_xml = render_odt_manifest(images);
    let mut members = vec![
        StoredZipMember::new("mimetype", "application/vnd.oasis.opendocument.text"),
        StoredZipMember::new("content.xml", content_xml),
        StoredZipMember::new("styles.xml", render_odt_styles()),
        StoredZipMember::new("meta.xml", render_odt_meta(export)),
        StoredZipMember::new("META-INF/manifest.xml", manifest_xml),
    ];
    for image in images {
        members.push(StoredZipMember::new(
            format!("Pictures/{}", image.file_name),
            image.bytes.clone(),
        ));
    }
    build_stored_zip_archive(&members)
}

pub(crate) fn render_docx(
    export: &LabAssistantInstructionsExport,
    images: &[LabAssistantEmbeddedImage],
) -> Result<Vec<u8>, String> {
    let mut members = vec![
        StoredZipMember::new("[Content_Types].xml", render_docx_content_types(images)),
        StoredZipMember::new("_rels/.rels", render_docx_root_relationships()),
        StoredZipMember::new("docProps/core.xml", render_docx_core(export)),
        StoredZipMember::new("docProps/app.xml", render_docx_app()),
        StoredZipMember::new("word/document.xml", render_docx_document(export, images)),
        StoredZipMember::new(
            "word/_rels/document.xml.rels",
            render_docx_document_relationships(images),
        ),
        StoredZipMember::new("word/styles.xml", render_docx_styles()),
    ];
    for image in images {
        members.push(StoredZipMember::new(
            format!("word/media/{}", image.file_name),
            image.bytes.clone(),
        ));
    }
    build_stored_zip_archive(&members)
}

fn push_markdown_visuals(out: &mut String, export: &LabAssistantInstructionsExport) {
    if export.embedded_visuals.is_empty() {
        return;
    }
    out.push_str("## Visual Overview\n\n");
    for visual in &export.embedded_visuals {
        out.push_str(&format!(
            "- {} [{}; {}; {}x{} px]\n",
            markdown_escape(&visual.label),
            markdown_escape(&visual.format),
            markdown_escape(&visual.source),
            visual.width_px,
            visual.height_px
        ));
    }
    out.push('\n');
}

fn push_markdown_materials(out: &mut String, export: &LabAssistantInstructionsExport) {
    out.push_str("## Materials and IDs\n\n");
    if export.material_rows.is_empty() {
        out.push_str("- No material rows were available in the selected GENtle state.\n\n");
    } else {
        for row in &export.material_rows {
            let mut detail = format!(
                "- `{}`: {} [{}; source={}]",
                markdown_escape(&row.material_id),
                markdown_escape(&row.display_name),
                markdown_escape(&row.kind),
                markdown_escape(&row.source)
            );
            if let Some(length_bp) = row.length_bp {
                detail.push_str(&format!("; {length_bp} bp"));
            }
            if let Some(topology) = row.topology.as_deref() {
                detail.push_str(&format!("; {}", markdown_escape(topology)));
            }
            if !row.members.is_empty() {
                detail.push_str(&format!(
                    "; members: {}",
                    row.members
                        .iter()
                        .map(|value| format!("`{}`", markdown_escape(value)))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            out.push_str(&detail);
            out.push('\n');
            for note in &row.notes {
                out.push_str(&format!("  - {}\n", markdown_escape(note)));
            }
        }
        out.push('\n');
    }
}

fn push_markdown_list(out: &mut String, heading: &str, lines: &[String]) {
    out.push_str(&format!("## {heading}\n\n"));
    if lines.is_empty() {
        out.push_str("- None recorded.\n\n");
        return;
    }
    for line in lines {
        out.push_str(&format!("- {}\n", markdown_escape(line)));
    }
    out.push('\n');
}

fn markdown_escape(value: &str) -> String {
    value.replace(['\n', '\r'], " ")
}

fn xml_escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&apos;"),
            _ => out.push(ch),
        }
    }
    out
}

fn odt_paragraph(text: &str) -> String {
    format!("<text:p>{}</text:p>", xml_escape(text))
}

fn odt_heading(level: usize, text: &str) -> String {
    format!(
        "<text:h text:outline-level=\"{}\">{}</text:h>",
        level,
        xml_escape(text)
    )
}

fn push_odt_lines(out: &mut String, heading: &str, lines: &[String]) {
    out.push_str(&odt_heading(2, heading));
    if lines.is_empty() {
        out.push_str(&odt_paragraph("None recorded."));
        return;
    }
    for line in lines {
        out.push_str(&odt_paragraph(&format!("- {line}")));
    }
}

fn render_odt_content(
    export: &LabAssistantInstructionsExport,
    images: &[LabAssistantEmbeddedImage],
) -> String {
    let mut body = String::new();
    body.push_str(&odt_heading(1, &export.title));
    body.push_str(&odt_paragraph(&format!("Schema: {}", export.schema)));
    body.push_str(&odt_paragraph(&format!(
        "Format: {}",
        export.output_format.as_str()
    )));
    body.push_str(&odt_paragraph(&format!("Audience: {}", export.audience)));
    body.push_str(&odt_paragraph(
        "Generated by GENtle from selected operation records.",
    ));
    if let Some(run_id) = export.run_id_filter.as_deref() {
        body.push_str(&odt_paragraph(&format!("Run ID: {run_id}")));
    }
    push_odt_lines(&mut body, "Summary", &export.summary_lines);
    push_odt_lines(&mut body, "Safety and Scope", &export.safety_lines);
    if !images.is_empty() {
        body.push_str(&odt_heading(2, "Visual Overview"));
        for image in images {
            let (width_in, height_in) = image_size_inches(image);
            body.push_str(&format!(
                "<text:p><draw:frame draw:name=\"{}\" text:anchor-type=\"paragraph\" svg:width=\"{:.3}in\" svg:height=\"{:.3}in\" draw:style-name=\"fr1\"><draw:image xlink:href=\"Pictures/{}\" xlink:type=\"simple\" xlink:show=\"embed\" xlink:actuate=\"onLoad\"/></draw:frame></text:p>",
                xml_escape(&image.visual_id),
                width_in,
                height_in,
                xml_escape(&image.file_name)
            ));
            body.push_str(&odt_paragraph(&image.label));
        }
    }
    body.push_str(&odt_heading(2, "Materials and IDs"));
    if export.material_rows.is_empty() {
        body.push_str(&odt_paragraph(
            "No material rows were available in the selected GENtle state.",
        ));
    } else {
        for row in &export.material_rows {
            let mut line = format!(
                "{}: {} [{}; source={}]",
                row.material_id, row.display_name, row.kind, row.source
            );
            if let Some(length_bp) = row.length_bp {
                line.push_str(&format!("; {length_bp} bp"));
            }
            if let Some(topology) = row.topology.as_deref() {
                line.push_str(&format!("; {topology}"));
            }
            if !row.members.is_empty() {
                line.push_str(&format!("; members: {}", row.members.join(", ")));
            }
            body.push_str(&odt_paragraph(&format!("- {line}")));
            for note in &row.notes {
                body.push_str(&odt_paragraph(&format!("  - {note}")));
            }
        }
    }
    for section in &export.step_sections {
        push_odt_lines(&mut body, &section.heading, &section.steps);
    }
    push_odt_lines(&mut body, "Checkpoints", &export.checkpoint_lines);
    push_odt_lines(&mut body, "Record Keeping", &export.record_keeping_lines);
    if !export.warning_lines.is_empty() {
        push_odt_lines(&mut body, "Warnings", &export.warning_lines);
    }

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><office:document-content xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\" office:version=\"1.2\"><office:automatic-styles><style:style style:name=\"fr1\" style:family=\"graphic\"><style:graphic-properties style:vertical-pos=\"top\" style:vertical-rel=\"paragraph\" style:horizontal-pos=\"center\" style:horizontal-rel=\"paragraph\"/></style:style></office:automatic-styles><office:body><office:text>{body}</office:text></office:body></office:document-content>"
    )
}

fn render_odt_styles() -> String {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><office:document-styles xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0\" office:version=\"1.2\"><office:styles><style:default-style style:family=\"paragraph\"><style:text-properties fo:font-family=\"Liberation Serif\" fo:font-size=\"11pt\"/></style:default-style></office:styles></office:document-styles>".to_string()
}

fn render_odt_meta(export: &LabAssistantInstructionsExport) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><office:document-meta xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" office:version=\"1.2\"><office:meta><dc:title>{}</dc:title><meta:generator>GENtle</meta:generator></office:meta></office:document-meta>",
        xml_escape(&export.title)
    )
}

fn render_odt_manifest(images: &[LabAssistantEmbeddedImage]) -> String {
    let mut entries = String::new();
    entries.push_str("<manifest:file-entry manifest:full-path=\"/\" manifest:media-type=\"application/vnd.oasis.opendocument.text\"/>");
    entries.push_str("<manifest:file-entry manifest:full-path=\"content.xml\" manifest:media-type=\"text/xml\"/>");
    entries.push_str(
        "<manifest:file-entry manifest:full-path=\"styles.xml\" manifest:media-type=\"text/xml\"/>",
    );
    entries.push_str(
        "<manifest:file-entry manifest:full-path=\"meta.xml\" manifest:media-type=\"text/xml\"/>",
    );
    for image in images {
        entries.push_str(&format!(
            "<manifest:file-entry manifest:full-path=\"Pictures/{}\" manifest:media-type=\"image/png\"/>",
            xml_escape(&image.file_name)
        ));
    }
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?><manifest:manifest xmlns:manifest=\"urn:oasis:names:tc:opendocument:xmlns:manifest:1.0\" manifest:version=\"1.2\">{entries}</manifest:manifest>"
    )
}

fn docx_paragraph(style: Option<&str>, text: &str) -> String {
    let style = style
        .map(|value| format!("<w:pPr><w:pStyle w:val=\"{}\"/></w:pPr>", xml_escape(value)))
        .unwrap_or_default();
    format!(
        "<w:p>{style}<w:r><w:t>{}</w:t></w:r></w:p>",
        xml_escape(text)
    )
}

fn push_docx_lines(out: &mut String, heading: &str, lines: &[String]) {
    out.push_str(&docx_paragraph(Some("Heading2"), heading));
    if lines.is_empty() {
        out.push_str(&docx_paragraph(None, "None recorded."));
        return;
    }
    for line in lines {
        out.push_str(&docx_paragraph(None, &format!("- {line}")));
    }
}

fn render_docx_document(
    export: &LabAssistantInstructionsExport,
    images: &[LabAssistantEmbeddedImage],
) -> String {
    let mut body = String::new();
    body.push_str(&docx_paragraph(Some("Title"), &export.title));
    body.push_str(&docx_paragraph(None, &format!("Schema: {}", export.schema)));
    body.push_str(&docx_paragraph(
        None,
        &format!("Format: {}", export.output_format.as_str()),
    ));
    body.push_str(&docx_paragraph(
        None,
        &format!("Audience: {}", export.audience),
    ));
    body.push_str(&docx_paragraph(
        None,
        "Generated by GENtle from selected operation records.",
    ));
    if let Some(run_id) = export.run_id_filter.as_deref() {
        body.push_str(&docx_paragraph(None, &format!("Run ID: {run_id}")));
    }
    push_docx_lines(&mut body, "Summary", &export.summary_lines);
    push_docx_lines(&mut body, "Safety and Scope", &export.safety_lines);
    if !images.is_empty() {
        body.push_str(&docx_paragraph(Some("Heading2"), "Visual Overview"));
        for (idx, image) in images.iter().enumerate() {
            body.push_str(&docx_image_paragraph(image, idx + 1));
            body.push_str(&docx_paragraph(None, &image.label));
        }
    }
    body.push_str(&docx_paragraph(Some("Heading2"), "Materials and IDs"));
    if export.material_rows.is_empty() {
        body.push_str(&docx_paragraph(
            None,
            "No material rows were available in the selected GENtle state.",
        ));
    } else {
        for row in &export.material_rows {
            let mut line = format!(
                "{}: {} [{}; source={}]",
                row.material_id, row.display_name, row.kind, row.source
            );
            if let Some(length_bp) = row.length_bp {
                line.push_str(&format!("; {length_bp} bp"));
            }
            if let Some(topology) = row.topology.as_deref() {
                line.push_str(&format!("; {topology}"));
            }
            if !row.members.is_empty() {
                line.push_str(&format!("; members: {}", row.members.join(", ")));
            }
            body.push_str(&docx_paragraph(None, &format!("- {line}")));
            for note in &row.notes {
                body.push_str(&docx_paragraph(None, &format!("  - {note}")));
            }
        }
    }
    for section in &export.step_sections {
        push_docx_lines(&mut body, &section.heading, &section.steps);
    }
    push_docx_lines(&mut body, "Checkpoints", &export.checkpoint_lines);
    push_docx_lines(&mut body, "Record Keeping", &export.record_keeping_lines);
    if !export.warning_lines.is_empty() {
        push_docx_lines(&mut body, "Warnings", &export.warning_lines);
    }

    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:document xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:wp=\"http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing\" xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:pic=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><w:body>{body}<w:sectPr><w:pgSz w:w=\"12240\" w:h=\"15840\"/><w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"720\" w:footer=\"720\" w:gutter=\"0\"/></w:sectPr></w:body></w:document>"
    )
}

fn docx_image_paragraph(image: &LabAssistantEmbeddedImage, relationship_index: usize) -> String {
    let (cx, cy) = image_size_emu(image);
    let rel_id = format!("rIdImage{relationship_index}");
    format!(
        "<w:p><w:r><w:drawing><wp:inline distT=\"0\" distB=\"0\" distL=\"0\" distR=\"0\"><wp:extent cx=\"{cx}\" cy=\"{cy}\"/><wp:docPr id=\"{relationship_index}\" name=\"{}\"/><a:graphic><a:graphicData uri=\"http://schemas.openxmlformats.org/drawingml/2006/picture\"><pic:pic><pic:nvPicPr><pic:cNvPr id=\"0\" name=\"{}\"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed=\"{rel_id}\"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"{cx}\" cy=\"{cy}\"/></a:xfrm><a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r></w:p>",
        xml_escape(&image.label),
        xml_escape(&image.file_name)
    )
}

fn render_docx_content_types(images: &[LabAssistantEmbeddedImage]) -> String {
    let png_default = if images.is_empty() {
        String::new()
    } else {
        "<Default Extension=\"png\" ContentType=\"image/png\"/>".to_string()
    };
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/>{png_default}<Override PartName=\"/word/document.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml\"/><Override PartName=\"/word/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml\"/><Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/><Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/></Types>"
    )
}

fn render_docx_root_relationships() -> String {
    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"word/document.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/><Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/></Relationships>".to_string()
}

fn render_docx_document_relationships(images: &[LabAssistantEmbeddedImage]) -> String {
    let mut relationships = String::from(
        "<Relationship Id=\"rIdStyles\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>",
    );
    for (idx, image) in images.iter().enumerate() {
        relationships.push_str(&format!(
            "<Relationship Id=\"rIdImage{}\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/image\" Target=\"media/{}\"/>",
            idx + 1,
            xml_escape(&image.file_name)
        ));
    }
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">{relationships}</Relationships>"
    )
}

fn render_docx_core(export: &LabAssistantInstructionsExport) -> String {
    format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dcmitype=\"http://purl.org/dc/dcmitype/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><dc:title>{}</dc:title><dc:creator>GENtle</dc:creator></cp:coreProperties>",
        xml_escape(&export.title)
    )
}

fn render_docx_app() -> String {
    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\"><Application>GENtle</Application></Properties>".to_string()
}

fn render_docx_styles() -> String {
    "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><w:styles xmlns:w=\"http://schemas.openxmlformats.org/wordprocessingml/2006/main\"><w:style w:type=\"paragraph\" w:styleId=\"Title\"><w:name w:val=\"Title\"/><w:rPr><w:b/><w:sz w:val=\"36\"/></w:rPr></w:style><w:style w:type=\"paragraph\" w:styleId=\"Heading2\"><w:name w:val=\"heading 2\"/><w:rPr><w:b/><w:sz w:val=\"28\"/></w:rPr></w:style></w:styles>".to_string()
}

fn image_size_inches(image: &LabAssistantEmbeddedImage) -> (f64, f64) {
    let max_width = 6.5f64;
    let width = image.width_px.max(1) as f64;
    let height = image.height_px.max(1) as f64;
    let rendered_height = (max_width * height / width).min(4.5);
    (max_width, rendered_height)
}

fn image_size_emu(image: &LabAssistantEmbeddedImage) -> (u64, u64) {
    let (width_in, height_in) = image_size_inches(image);
    (
        (width_in * 914_400.0).round() as u64,
        (height_in * 914_400.0).round() as u64,
    )
}
